package report

const (
	ReportCovPrefix = "apkoverage:"
)

// CovReport represents the report generated by the tool.
type CovReport struct {
	// The package name.
	PkgName string `json:"pkg_name"`
	// The package version.
	PkgVersion string `json:"pkg_version"`
	// The package revision aka epoch.
	PkgEpoch uint64 `json:"pkg_epoch"`
	// The coverage of the package provided by the Melange test pipeline,
	// expressed as float64 of statements of the main software packaged.
	CovFloat float64 `json:"cov_float"`
}

type CovReportPackage struct {
}

func NewCovReport(opts ...CovReportOption) *CovReport {
	report := new(CovReport)
	for _, f := range opts {
		f(report)
	}

	return report
}

type CovReportOption func(*CovReport)

func WithPackageName(name string) CovReportOption {
	return func(r *CovReport) {
		r.PkgName = name
	}
}

func WithPackageVersion(version string) CovReportOption {
	return func(r *CovReport) {
		r.PkgVersion = version
	}
}

func WithPackageEpoch(epoch uint64) CovReportOption {
	return func(r *CovReport) {
		r.PkgEpoch = epoch
	}
}

func WithCovPercent(cov float64) CovReportOption {
	return func(r *CovReport) {
		r.CovFloat = cov
	}
}
